Repository dev-floor/hongit_fe, pull requests merged in 2021-05, with the labels that each got.

#29 feature(api): api 모듈 생성
  package.json
  src/Article/container/ArticleHeaderContainer.tsx
  src/Article/container/AuthorInfoContainer.tsx
  src/Article/container/CommentContainer.tsx
  src/api/api.ts
  src/data/articleInfo.json
  src/data/articleList.json
  src/data/commentList.json
Labels: 🚀 enhancement

#15 feature(게시물 상세 조회): 게시물 상세 페이지 바디 컴포넌트 개발
  package.json
  src/App.tsx
  src/Article/container/ArticleBodyContainer.tsx
  src/Article/css/ArticleBody.css
  src/Article/css/AuthorInfo.css
  src/Article/presentational/ArticleBody.tsx
  src/Article/presentational/AuthorInfo.tsx
  yarn.lock
Labels: 🚀 enhancement

#31 feature(게시판 게시글 목록 조회): React Router 도입
  package.json
  src/App.css
  src/App.tsx
  src/Article/container/ArticleBodyContainer.tsx
  src/Article/css/ArticleBody.css
  src/Article/css/ArticleCreatePage.css
  src/Article/css/ArticleHeader.css
  src/Article/css/AuthorInfo.css
  src/Article/css/CommentArea.css
  src/Article/presentational/ArticleBody.tsx
  src/Article/presentational/ArticleDetail.tsx
  src/Article/presentational/AuthorInfo.tsx
  src/Article/presentational/CommentArea.tsx
  src/Router.css
  src/Router.tsx
  src/RouterTest.tsx
  src/api/ApiProps.tsx
  src/data/articleInfo.json
  src/data/commentList.json
  src/index.tsx
  tsconfig.json
Labels: 🚀 enhancement

#32 feature(게시판 게시글 목록 조회): ArticleArea Component 개발
  src/Article/presentational/ArticleDetail.tsx
  src/ArticleList/argumentsPropsInterface/ArticleListProps.tsx
  src/ArticleList/container/ArticleListContainer.tsx
  src/ArticleList/css/ArticleList.css
  src/ArticleList/presentational/ArticleList.tsx
  src/Router.tsx
  src/api/ApiProps.tsx
  src/data/articleList.json
  src/interface/routerInterface.ts
Labels: 🚀 enhancement

#36 refactor: react router 관련 페이지 이동 기능 수정 개발
  src/App.tsx
  src/Article/argumentsPropsInterface/ArticleProps.tsx
  src/Article/container/ArticleBodyContainer.tsx
  src/Article/container/ArticleCreatePageContainer.tsx
  src/Article/presentational/ArticleCreatePage.tsx
  src/Article/presentational/ArticleDetail.tsx
  src/ArticleList/presentational/ArticleList.tsx
  src/RouterTest.tsx
  src/api/api.ts
  src/data/ArticleInfoDummyData.ts
  src/data/ArticleListDummyData.ts
  src/data/CommentListDummyData.ts
  src/data/articleInfo.json
  src/data/articleList.json
  src/data/commentList.json
  src/interface/routerInterface.ts
Labels: 🛠 refactoring

#38 feature(게시물 상세 조회): 수정, 삭제 버튼 생성, 및 useParams 함수 타입 수정.
  src/Article/argumentsPropsInterface/ArticleProps.tsx
  src/Article/container/ArticleHeaderContainer.tsx
  src/Article/presentational/ArticleDetail.tsx
  src/Article/presentational/ArticleHeader.tsx
  src/RouterTest.tsx
Labels: 🚀 enhancement

#39 feature(CSS): CSS 통합 및 구조 변경
  craco.config.js
  package.json
  src/Article/container/ArticleBodyContainer.tsx
  src/Article/container/ArticleHeaderContainer.tsx
  src/Article/container/AuthorInfoContainer.tsx
  src/Article/css/ArticleBody.css
  src/Article/css/ArticleCreatePage.css
  src/Article/css/ArticleHeader.css
  src/Article/css/AuthorInfo.css
  src/Article/css/CommentArea.css
  src/Article/css/FloatingButton.css
  src/Article/presentational/ArticleBody.tsx
  src/Article/presentational/ArticleCreatePage.tsx
  src/Article/presentational/ArticleDetail.tsx
  src/Article/presentational/ArticleHeader.tsx
  src/Article/presentational/AuthorInfo.tsx
  src/Article/presentational/CommentArea.tsx
  src/Article/presentational/FloatingButton.tsx
  src/ArticleList/css/ArticleList.css
  src/ArticleList/presentational/ArticleList.tsx
  src/css/Article.css
  src/css/ArticleList.css
  src/css/common.css
  src/data/ArticleInfoDummyData.ts
  src/data/ArticleListDummyData.ts
  tsconfig.json
  tsconfig.paths.json
Labels: 🗻 environment, 🛠 refactoring

#44 feature(알림창 컴포넌트 생성) react-modal 창 컴포넌트 구성
  README.md
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/Article/argumentsPropsInterface/ArticleProps.tsx
  src/Article/container/ArticleCreatePageContainer.tsx
  src/Article/container/CommentContainer.tsx
  src/Article/presentational/CommentArea.tsx
  src/Commons/Modal.tsx
  src/Router.css
  src/Router.tsx
  src/RouterTest.tsx
  src/css/Article.css
  src/css/Modal.css
  src/css/common.css
  src/css/index.css
  src/index.tsx
Labels: 🚀 enhancement

#43 feature(게시물 상세 조회): 게시물 수정 기능 구현
  package.json
  src/Article/argumentsPropsInterface/ArticleProps.tsx
  src/Article/container/ArticleBodyContainer.tsx
  src/Article/container/ArticleCreatePageContainer.tsx
  src/Article/container/ArticleDetailContainer.tsx
  src/Article/container/ArticleHeaderContainer.tsx
  src/Article/container/AuthorInfoContainer.tsx
  src/Article/container/CommentContainer.tsx
  src/Article/presentational/ArticleCreatePage.tsx
  src/Article/presentational/ArticleHeader.tsx
  src/Article/presentational/CommentArea.tsx
  src/Router.tsx
  src/data/ArticleInfoDummyData.ts
Labels: 🚀 enhancement

#47 feature(게시물 상세 조회): 댓글 컴포넌트 수정/삭제
  src/App.tsx
  src/Article/argumentsPropsInterface/ArticleProps.tsx
  src/Article/container/CommentContainer.tsx
  src/Article/presentational/ArticleHeader.tsx
  src/Article/presentational/CommentArea.tsx
  src/ArticleList/presentational/ArticleList.tsx
  src/Commons/Modal.tsx
  src/api/api.ts
  src/css/Article.css
Labels: 🚀 enhancement
