Repository dev-floor/hongit_fe, pull requests merged in 2021-04, with the labels that each got.

#6 feat(environment): 초기 개발 환경 설정 개발
  .eslintignore
  .eslintrc
  .gitignore
  .prettierrc
  README.md
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: 🗻 environment

#7 docs(template): 기존 이슈 탬플릿 수정 및 사용하지 않는 탬플릿 제거
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: 📝 documentation

#8 docs(template): 이슈 탬플릿 수정
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: 📝 documentation

#14 feature(게시물 상세 조회): 게시물 상세 페이지 헤더 컴포넌트 개발
  package.json
  src/App.css
  src/App.tsx
  src/Article/container/ArticleHeaderContainer.tsx
  src/Article/container/AuthorInfo.tsx
  src/Article/css/ArticleHeader.css
  src/Article/css/AuthorInfo.css
  src/Article/presentational/ArticleHeader.tsx
  src/api/ApiProps.tsx
  src/data/articleInfo.json
  src/index.tsx
  tsconfig.json
Labels: 🚀 enhancement

#16 feature(게시글 상세 조회): 작성자 컴포넌트 개발
  .gitignore
  src/App.tsx
  src/Article/container/AuthorInfoContainer.tsx
  src/Article/css/AuthorInfo.css
  src/Article/presentational/AuthorInfo.tsx
  src/data/articleInfo.json
Labels: 🚀 enhancement

#18 feature(게시글 상세 조회): 댓글 컴포넌트 기능 구현
  .eslintrc
  package.json
  src/App.tsx
  src/Article/argumentsPropsInterface/ArticleProps.tsx
  src/Article/container/CommentContainer.tsx
  src/Article/css/ArticleHeader.css
  src/Article/css/CommentArea.css
  src/Article/presentational/CommentArea.tsx
  src/api/ApiProps.tsx
  src/data/articleInfo.json
  src/data/commentList.json
  yarn.lock
Labels: 🚀 enhancement

#21 style: prettier 적용
  package.json
  src/App.tsx
  src/Article/argumentsPropsInterface/ArticleProps.tsx
  src/Article/container/ArticleHeaderContainer.tsx
  src/Article/container/AuthorInfoContainer.tsx
  src/Article/container/CommentContainer.tsx
  src/Article/css/ArticleHeader.css
  src/Article/css/AuthorInfo.css
  src/Article/css/CommentArea.css
  src/Article/presentational/ArticleHeader.tsx
  src/Article/presentational/AuthorInfo.tsx
  src/Article/presentational/CommentArea.tsx
  src/api/ApiProps.tsx
  src/data/articleInfo.json
  src/data/commentList.json
Labels: 🛠 refactoring

#28 feature(라이브러리): Recoil 사용 준비 환경 세팅
  package.json
  src/index.tsx
Labels: 🗻 environment

#22 feature(게시글 상세 조회): 댓글 컴포넌트 구조 구현
  public/logo.svg
  src/Article/css/CommentArea.css
  src/Article/presentational/CommentArea.tsx
  src/api/ApiProps.tsx
Labels: 🚀 enhancement
