Repository dev-floor/hongit_fe, pull requests merged in 2021-09, with the labels that each got.

#103 refactor: Refactored. (#102)
  package.json
  src/Article/container/ArticleBodyContainer.tsx
  src/Article/container/ArticleDetailContainer.tsx
  src/Article/container/ArticleHeaderContainer.tsx
  src/Article/container/AuthorInfoContainer.tsx
  src/Article/container/CommentContainer.tsx
  src/Article/presentational/ArticleBody.tsx
  src/Article/presentational/ArticleHeader.tsx
  src/Article/presentational/AuthorInfo.tsx
  src/Article/presentational/CommentArea.tsx
  src/ArticleList/presentational/ArticleList.tsx
  src/Board/presentational/AllLectureMenu.tsx
  src/Board/presentational/BoardPreview.tsx
  src/Board/presentational/MyLecture.tsx
  src/Commons/FilterModal.tsx
  src/Layout/Container/HongitMainContainer.tsx
  src/Layout/Presentational/Sidebar.tsx
  src/interface/ArgProps.tsx
Labels: 🛠 refactoring

#101 feature(회원가입): 입력 태그마다 상황별 메시지 추가 및 css 수정
  src/User/Presentational/SignIn.tsx
  src/css/SignIn.css
Labels: 🚀 enhancement, 🛠 refactoring

#106 refactor(게시판 목록 조회): API 명세 업데이트 반영
  src/api/ApiProps.tsx
  src/data/SideBarDummyData.ts
Labels: 🛠 refactoring

#105 refactor: 코드최적화 및 API 도입
  src/Article/container/ArticleBodyContainer.tsx
  src/Article/container/ArticleCreatePageContainer.tsx
  src/Article/container/ArticleDetailContainer.tsx
  src/Article/container/ArticleHeaderContainer.tsx
  src/Article/container/AuthorInfoContainer.tsx
  src/Article/container/CommentContainer.tsx
  src/Article/presentational/ArticleBody.tsx
  src/Article/presentational/ArticleHeader.tsx
  src/Article/presentational/AuthorInfo.tsx
  src/ArticleList/container/ArticleListContainer.tsx
  src/Board/container/AllLectureMenuContainer.tsx
  src/Board/container/BoardDetailContainer.tsx
  src/Board/container/MyLectureContainer.tsx
  src/Commons/CalDiffTime.tsx
  src/Commons/TransferTimeFormat.tsx
  src/Layout/Container/HongitMainContainer.tsx
  src/Layout/Container/SidebarContainer.tsx
  src/User/Container/ProfileArticleContainer.tsx
  src/User/Container/ProfileCommentContainer.tsx
  src/User/Container/ProfileContainer.tsx
  src/User/Presentational/ProfileArticle.tsx
  src/User/Presentational/ProfileUser.tsx
  src/api/api.ts
  src/css/Article.css
  src/data/ArticleInfoDummyData.ts
  src/data/ArticleListDummyData.ts
  src/interface/ArgProps.tsx
Labels: 🚀 enhancement, 🛠 refactoring

#108 refactor: 잘못된 버튼 위치 조정
  src/Article/presentational/ArticleCreatePage.tsx
  src/css/Article.css
  src/css/Modal.css
Labels: 🛠 refactoring

#114 feature(token): bearer 추가
  src/Article/container/CommentContainer.tsx
  src/api/api.ts
Labels: 🚀 enhancement
